server:
  port: 8040

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Notification
      database: Notification

  mail:
    host: localhost        # maildev running locally
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        connectiontimeout: 5000
        writetimeout: 5000
        readtimeout: 5000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          OrderConfirmation:e_Commerce_project.Notification.Records.OrderConfirmation,
          PaymentConfirmation:e_Commerce_project.Notification.Records.PaymentConfirmation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: notification-service
